version: '3'

services:
  app:
    container_name: django-spy
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
        - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
    links:
        - "db:db"
    depends_on:
        - "db"

  db:
    container_name: postgresql_app
    image: postgres:14
    restart: always
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: